FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
ENV API_URL=http://localhost:8000
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf