version: "3.8"
services: #コンテナに対応
    go:
        container_name: go 
        build: ./golang #goのDockerfileのあるディレクトリを指定
        tty: true
        ports:
            - "8080:8080"
        env_file:
            - ./mysql/.env
        depends_on: #コンテナの起動順序を指定．
            - db
        volumes: #コンテナの外部に保管し．データを永続化する．
            - ./golang/app:/go/src/app
        networks: #コンテナ間の通信ができるようにする．
            - golang_test_network

    db:
        container_name: db
        build: ./mysql
        tty: true
        platform: linux/x86_64
        ports:
            - 3306:3306
        env_file:
            - ./mysql/.env
        volumes:
            - mysql_test_volume:/var/lib/mysql
        networks:
            - golang_test_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        container_name: phpmyadmin
        ports:
            - "8081:80"
        env_file:
            - ./mysql/.env
        environment:
            PMA_HOST: db
            PMA_USER: test_user
            PMA_PASSWORD: opinion
        depends_on:
            - db
        networks:
            - golang_test_network

volumes:
    mysql_test_volume:
        name: mysql_test_volume

networks:
    golang_test_network:
        external: true
